[project]
name = "Canopen Accu Viewer"
description = ""
dependencies = [
    "PySide6>=6.11",
    "pyserial>=3.5",
    "python-can>=4.6.1",
    "canopen>=2.4.1",
]
readme = "README.md"
requires-python = ">=3.11"


[tool.pyside6-project]
files = [
    "main.py",
    "application_controller.py",
    "canopen_app/can_service.py",
    "canopen_app/measurement_processor.py",
    "canopen_app/ui_adapter.py",
    "tools/canopen_client_short.py",
    "includes/Main.qml",
    "AnyComponent.qml",
    "GroupComponent.qml",
    "SettingsComponent.qml",
    "SidePanelContainer.qml",
    "includes/ButtonBar.qml",
    "includes/StatPanel.qml",
    "includes/DiagramPanel.qml",
    "includes/GraphMain.qml",
    "includes/GraphMinMax.qml",
    "includes/Theme.qml",
    "includes/QtGraphAutoAxisY.js",
]

[tool.coverage.run]
omit = [
    "*shibokensupport*",
    "*signature_bootstrap*",
    "*pyscript*",
]
disable_warnings = ["couldnt-parse"]

[tool.coverage.report]
ignore_errors = true
omit = [
    "*shibokensupport*",
    "*signature_bootstrap*",
    "*pyscript*",
]
